repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: readsimulator
  description: This pipeline simulates reads from short-read Illumina data.
  author: Rob Linder
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
