contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #readsimulator channel"
    url: https://nfcore.slack.com/channels/readsimulator
    about: Discussion about the nf-core/readsimulator pipeline
